CREATE TABLE `users` (
  `uid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE KEY,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `gender` ENUM('M','F') NOT NULL DEFAULT 'M',
  `bio` TEXT DEFAULT 'Hey, I am new here.',
  `avatar` LONGTEXT DEFAULT NULL DEFAULT 'male.jpg',
  `online` TINYINT(1) DEFAULT NULL,
  `lastlogin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `joindate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `posts` (
  `pid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` INT NOT NULL REFERENCES `users`(`uid`) ON DELETE CASCADE,
  `text` TEXT NOT NULL,
  `photo` LONGTEXT DEFAULT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `alerts` (
  `aid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` INT NOT NULL REFERENCES `users`(`uid`) ON DELETE CASCADE,
  `pid` INT REFERENCES `posts`(`pid`) ON DELETE CASCADE,
  `text` TEXT NOT NULL,
  `status` ENUM('read','unread') NOT NULL DEFAULT 'unread',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `reactions` (
  `rid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` INT NOT NULL REFERENCES `users`(`uid`) ON DELETE CASCADE,
  `pid` INT NOT NUll REFERENCES `posts`(`pid`) ON DELETE CASCADE,
  UNIQUE KEY (`uid`,`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `comments` (
  `cid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` INT NOT NULL REFERENCES `users`(`uid`) ON DELETE CASCADE,
  `pid` INT NOT NUll REFERENCES `posts`(`pid`) ON DELETE CASCADE,
  `text` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `messages` (
  `mid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` INT NOT NULL REFERENCES `users`(`uid`) ON DELETE CASCADE,
  `text` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
